//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> IDTeacher { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CodeClass { get; set; }
        public string IDCourse { get; set; }
        public string Level { get; set; }
        public Nullable<int> QuantityOfStudents { get; set; }
        public Nullable<int> TotalLessons { get; set; }
    }
}
