//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permision_Detail
    {
        public int ID { get; set; }
        public bool Add { get; set; }
        public bool Edit { get; set; }
        public bool Delete { get; set; }
        public Nullable<int> IDPermision { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
